-- POBLACIÓN MASIVA DE LA TABLA ESTUDIOS CON LOS 289 ESTUDIOS DE VIDAMED

INSERT INTO estudios (nombre, metodo, categoria, tiempo_entrega_elisa_otro, tiempo_entrega_quimioluminiscencia, costo_usd, tipo_de_muestra) VALUES
('17-CETOSTEROIDE', 'Colorimetría', 'Prueba Especial', '24 horas', 'N/A', 53, 'ORINA 24 HORAS'),
('17 OH PROGESTERONA', 'Quimioluminiscencia', 'Hormona Femenina', '24 horas', '3 horas', 20, 'SUERO'),
('(5-HIAA) ACIDO 5 HIDROXIINDOLACETICO', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 99, 'SUERO'),
('25 OH VITAMINA D', 'ELISA', 'Metabolismo Óseo', '24 horas', '3 horas', 25, 'SUERO'),
('ACTH', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 22, 'SUERO'),
('ACIDO LACTICO (LACTATO)', 'Enzimático', 'Química Sanguínea', '24 horas', 'N/A', 31, 'PLASMA EDTA'),
('ACIDO VANILMANDELICO', 'Colorimetría', 'Prueba Especial', '24 horas', 'N/A', 53, 'ORINA DE 24 HORAS/ORINA PARCIAL'),
('ACIDO VALPROICO', 'Quimioluminiscencia', 'Prueba Especial', '24 horas', '24 horas', 45, 'SUERO'),
('ADA (ADENOSINA DEAMINASA)', 'Colorimetría', 'Prueba Especial', '24 horas', 'N/A', 44, 'LIQUIDO PLEURAL'),
('ALFA 1 ANTITRIPSINA', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 55, 'SUERO/PLASMA'),
('ASPERGILLUS IgG', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 44, 'SUERO'),
('ANTIGENO VIRAL PARA SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2', 'Test Rápido', 'Prueba Especial', '24 horas', 'N/A', 16, 'HISOPADO NASAL'),
('ANTIGENOS PARA VIRUS Y BACTERIAS RESPIRATORIAS (COVID-19, INFLUENZA A+B, RSV, MYCOPLASMA PNEUMONIAE)', 'Test Rápido', 'Prueba Rápida', '24 horas', 'N/A', 50, 'HISOPADO NASAL'),
('ANTI-MCV (La Vimentina Citrulinada Mutada)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 50, 'SUERO'),
('ANTIGENO VIRAL PARA SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2 EN SALIVA', 'Test Rápido', 'Prueba Especial', '24 horas', 'N/A', 39, 'SALIVA'),
('ANTICUERPOS NEUTRALIZANTES CONTRA COVID-19', 'Inmunofluorescencia', 'Prueba Especial', '24 horas', 'N/A', 28, 'SUERO'),
('ALDOSTERONA', 'ELISA', 'Metabolismo Renal', '24 horas', 'N/A', 50, 'ORINA/SUERO'),
('ANAPLASMA', 'Frotis de Capa Blanca', 'Prueba Especial', '24 horas', 'N/A', 16, 'PLASMA EDTA'),
('ANION GAP', 'Turbidimetría', 'Metabolismo Renal', '24 horas', 'N/A', 38, 'ORINA'),
('ANCA C (ANTI PR3)', 'ELISA', 'Autoinmunidad', '24 horas', 'N/A', 27, 'SUERO'),
('ANCA P (ANTI-MPO)', 'ELISA', 'Autoinmunidad', '24 horas', 'N/A', 27, 'SUERO'),
('ANTIGENO DEL VIRUS SINCITIAL RESPIRATORIO (RSV)', 'Prueba Rápida', 'Pruebas Infecciosas', '24 horas', 'N/A', 31, 'SUERO'),
('ANTICUERPOS ANTI NUCLEARES ANA PATRON (HEP2)', 'Inmunofluorescencia', 'Autoinmunidad', '24 horas', 'N/A', 52, 'SUERO'),
('ANTICUERPOS ANTI-ENDOMISIALES (EMA) IgA', 'ELISA', 'Autoinmunidad', '24 horas', 'N/A', 34, 'SUERO'),
('ANTICUERPOS ANTI-ENDOMISIALES (EMA) IgG', 'ELISA', 'Autoinmunidad', '24 horas', 'N/A', 34, 'SUERO'),
('ANTICUERPOS ANTI-MITOCONDRIALES (AMA)', 'INMUNOBLOT', 'Autoinmunidad', '24 horas', 'N/A', 34, 'SUERO'),
('ANTICUERPO SARS-CoV 2 IgM', 'ELISA', 'Infecciosas', '24 horas', 'N/A', 31, 'SUERO'),
('ANTICUERPO SARS-CoV 2 IgA', 'ELISA', 'Infecciosas', '24 horas', 'N/A', 31, 'SUERO'),
('ANTICUERPO SARS-CoV 2 IgG', 'ELISA', 'Infecciosas', '24 horas', 'N/A', 31, 'SUERO'),
('ANDROSTENEDIONA', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 24, 'SUERO'),
('ANTIGENOS FEBRILES (REACCION DE WIDAL)', 'Aglutinación', 'Prueba Especial', '12 horas', 'N/A', 15, 'SUERO'),
('A.S.T.O', 'Aglutinación', 'Serología', '12 horas', 'N/A', 7, 'SUERO'),
('ACIDO URICO', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('ALBUMINA EN SUERO', 'SUERO', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('ALFA-FETOPROTEÍNA (AFP)', 'ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('AMILASA', 'Enzimático', 'Química Sanguínea', '12 horas', 'N/A', 10, 'SUERO'),
('AMONIO', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 45, 'PLASMA CON EDTA'),
('ANA SCREEN IgG', 'Quimioluminiscencia', 'Perfil Autoinmune', '24 horas', '3 horas', 27, 'SUERO'),
('ANA WESTERN BLOT 14 ANTIGENOS (SS-A52/JO-1,SM.CENP-B,HISTONA, PM/SCL100, RIB., DSDNA, SCL-70, U1-SNRNP, SO SS-A60, MI-2, KU)', 'INMUNOBLOT', 'Perfil Autoinmune', '24 horas', 'N/A', 90, 'SUERO'),
('ANTI JO-1', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 27, 'SUERO'),
('ANTI-BETA 2 GLYCOPROTEINA IgG', 'Quimioluminiscencia', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTI-BETA 2 MICROGLOBULINA', 'ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 22, 'SUERO'),
('ANTI-CCP', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 27, 'SUERO'),
('ANTI-SM', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 21, 'SUERO'),
('ANTI-SSA (RO)', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 21, 'SUERO'),
('ANTI-SSB (LA)', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 21, 'SUERO'),
('ANTI-BETA 2 GLYCOPROTEINA IgM', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTI-CARDIOLIPINA IgM', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTI-CARDIOLIPINA IgG', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTI-FOSFOLIPIDOS IgM', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTI-FOSFOLIPIDOS IgG', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 24, 'SUERO'),
('ANTICOAGULANTE LUPICO', 'COAGULACIÓN', 'Perfil Autoinmune', '24 horas', 'N/A', 64, 'PLASMA CITRATADO'),
('ANTICUERPO CONTRA EL ANTIGENO DE SUPERFICIE DE LA HEPATITIS E (HBeAb)', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 16, 'SUERO'),
('ANTI-DS DNA IgG', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 27, 'SUERO'),
('ANTÍGENO CARCINOEMBRIONARIO (C.E.A)', 'Quimioluminiscencia/ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('ANTIGENO DE SUPERFICIE', 'Test Rápido', 'Pruebas Infecciosas', '24 horas', 'N/A', 16, 'SUERO'),
('ANTIGENO DE SUPERFICIE DE LA HEPATITIS E (HBeAg)', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 16, 'SUERO'),
('ANTI-GLIADINA DEAMINADA IgA GLIADINA SEGUNDA GENERACION', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 29, 'SUERO'),
('ANTI-GLIADINA DEAMINADA IgG GLIADINA SEGUNDA GENERACION', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 29, 'SUERO'),
('ANTI-SCL-70', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 29, 'SUERO'),
('ANTI-LKM1', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 38, 'SUERO'),
('ANTI-TIROGLOBULINA (ANTI-TG)', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 18, 'SUERO'),
('ANTI-TIROPEROXIDASA (ANTI-TPO)', 'Quimioluminiscencia/ELISA', 'Perfil Autoinmune', '24 horas', '3 horas', 18, 'SUERO'),
('ASCA IgA', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 46, 'SUERO'),
('ASCA IgG', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 46, 'SUERO'),
('AZUCARES REDUCTORES', 'Colorimetría', 'Coprología', '24 horas', 'N/A', 9, 'HECES'),
('Beta hCG (BhCG)', 'ELISA', 'Inmunofluorescencia/Quimioluminiscencia', '24 horas', '3 horas', 18, 'SUERO'),
('BILIRRUBINA TOTAL Y FRACCIONADA', 'Colorimetría', 'Química Sanguínea', '3 horas', 'N/A', 6, 'SUERO'),
('BORDETELLA IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 44, 'SUERO'),
('BUN (UREA)', 'Cinético', 'Química Sanguínea', '24 horas', 'N/A', 2, 'SUERO'),
('CITOGRAMA EN MOCO NASAL', 'Manual', 'Prueba Especial', '24 horas', 'N/A', 6, 'HISOPADO NASAL'),
('COOMBS DIRECTO', 'Aglutinación', 'Hematología', '24 horas', 'N/A', 6, 'SANGRE TOTAL'),
('COOMBS INDIRECTO', 'Aglutinación', 'Hematología', '24 horas', 'N/A', 6, 'SUERO'),
('CURVA DE FRAGILIDAD OSMOTICA', 'Colorimetría', 'Prueba Especial', '24 horas', 'N/A', 27, 'SUERO'),
('CATECOLAMINAS EN ORINA (DOPAMINA, ADRENALINA, NORADRENALINA)', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 220, 'PLASMA/ORINA DE 24 HORAS'),
('CALCITONINA', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 27, 'SUERO'),
('CA 125', 'Quimioluminiscencia/ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('CA 15-3', 'Quimioluminiscencia/ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('CA 72-4', 'Quimioluminiscencia/ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('CA 19-9', 'Quimioluminiscencia/ELISA', 'Marcadores Tumorales', '24 horas', '3 horas', 18, 'SUERO'),
('CALPROTECTINA', 'TEST RAPIDO', 'Coprología', '24 horas', 'N/A', 22, 'HECES'),
('CADENAS LIGERAS KAPPA Y LAMBDA', 'Inmunodifusión radial', 'Perfil Autoinmune', '72 horas', 'N/A', 50, 'ORINA PARCIAL'),
('CALCIO', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 3, 'SUERO'),
('CALCIO IONICO', 'Colorimetría', 'Química Sanguínea', '24 horas', 'N/A', 31, 'ORINA/SUERO'),
('CALCULOS URINARIOS Y CRISTALES URINARIOS (CALCIO, MAGNESIO, OXALATO, AMONIO, FOSFATO, CISTINA, ACIDO URICO)', 'Colorimetría', 'Química Sanguínea', '48 horas', 'N/A', 53, 'CALCULO URINARIO'),
('CARBAMAZEPINA', 'Quimioluminiscencia', 'Prueba Especial', '24 horas', 'N/A', 38, 'SUERO'),
('CELULAS NK Y NKT', 'Citometría de Flujo', 'Prueba Especial', '4 días hábiles', 'N/A', 170, 'SANGRE TOTAL'),
('CD3+CD4+CD8 (DETECCION CELULAR)', 'Citometría de Flujo', 'Prueba Especial', '4 días hábiles', 'N/A', 170, 'SANGRE TOTAL'),
('CELULAS LE', 'Aglutinación', 'Prueba Especial', '24 horas', 'N/A', 9, 'SUERO'),
('CISTATINA C', 'Inmunofluorescencia', 'Prueba Especial', '24 horas', 'N/A', 22, 'SUERO'),
('CH 50', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 48, 'SUERO'),
('CHAGAS', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 31, 'SUERO'),
('Chlamydia Pneumoniae IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('Chlamydia Pneumoniae IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('Chlamydia Trachomatis IgA', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 24, 'SUERO'),
('Chlamydia Trachomatis IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 24, 'SUERO'),
('Chlamydia Trachomatis IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 24, 'SUERO'),
('CITOQUIMICOS DE LIQUIDOS: (CEFALORRAQUIDEO, PLEURAL, SINOVIAL, PERICARDICO, ASITICO, PERITONEAL)', 'Manual', 'Prueba Especial', '24 horas', 'N/A', 27, 'LIQUIDO (CEFALORRAQUIDEO, PLEURAL, SINOVIAL, PERICARDICO, ASITICO, PERITONEAL)'),
('CITRATO EN ORINA', 'Colorimetría', 'Metabolismo Renal', '24 horas', 'N/A', 31, 'ORINA'),
('CTX-1 (Telopeptido C del Colageno tipo I)', 'Prueba Especial', 'Metabolismo Mineral Óseo', '24 horas', 'N/A', 53, 'SUERO/PLASMA'),
('CK', 'Colorimétrico', 'Marcador Cardiaco', '24 horas', 'N/A', 7, 'SUERO'),
('CK-MB', 'Enzimático', 'Marcador Cardiaco', '24 horas', 'N/A', 7, 'SUERO'),
('CLORO (CL)', 'Colorimetría', 'Química Sanguínea', '24 horas', 'N/A', 7, 'SUERO/ORINA'),
('CMV IgG (Cytomegalovirus)', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 13, 'SUERO'),
('CMV IgM (Cytomegalovirus)', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 13, 'SUERO'),
('COBRE (Cu)', 'Turbidimetría', 'Prueba Especial', '24 horas', 'N/A', 53, 'SUERO'),
('COCAINA EN ORINA', 'Test Rápido', 'Toxicología', '24 horas', 'N/A', 11, 'ORINA'),
('COLESTEROL TOTAL', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('COLINESTERASA', 'Cinético', 'Prueba Especial', '24 horas', 'N/A', 19, 'SUERO'),
('COMPLEMENTO C3', 'Inmunodifusión radial', 'Perfil Autoinmune', '72 horas', 'N/A', 13, 'SUERO'),
('COMPLEMENTO C4', 'Inmunodifusión radial', 'Perfil Autoinmune', '72 horas', 'N/A', 13, 'SUERO'),
('CONTAJE DE RETICULOCITOS', 'Manual', 'Hematología', '24 horas', 'N/A', 10, 'SANGRE TOTAL'),
('CORE IgM', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 16, 'SUERO'),
('CORE IgM + IgG (ANTICUERPOS TOTALES)', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 8, 'SUERO'),
('CORTISOL', 'ELISA/Quimioluminiscencia', 'Hormona', '24 horas', '3 horas', 16, 'SUERO'),
('CREATININA', 'Colorimetría', 'Química Sanguínea', '24 horas', '12 horas', 2, 'SUERO/ORINA'),
('CROMOGRANINA A', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 165, 'SUERO'),
('DIGOXINA', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 24, 'SUERO'),
('DENGUE IgM-IgG', 'Test Rápido', 'Pruebas Infecciosas', '24 horas', 'N/A', 11, 'SUERO'),
('DENGUE IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 11, 'SUERO'),
('DENGUE IgG', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 11, 'SUERO'),
('DEPURACION DE CREATININA', 'Colorimetría', 'Química Sanguínea', '24 horas', 'N/A', 18, 'ORINA 24 HORAS'),
('DEPURACION DE UREA', 'Colorimetría', 'Química Sanguínea', '24 horas', 'N/A', 18, 'ORINA'),
('DIHIDROTESTOSTERONA (DHT)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 57, 'SUERO'),
('DISBIOSIS INTESTINAL (Examen de Heces+ Helicobacter Pylori en Heces + Calprotectina+ IgA Secretora+ Zonulina)', 'Manual', 'Prueba Especial', '72 horas', 'N/A', 141, 'HECES'),
('DIMERO D', 'Turbidimetría', 'Prueba Especial', '24 horas', 'N/A', 18, 'PLASMA CITRATADO'),
('DHEA-S', 'Quimioluminiscencia/ELISA', 'Hormona Femenina', '24 horas', '3 horas', 18, 'SUERO'),
('ESTRIOL LIBRE', 'ELISA', 'Hormona Femenina', '24 horas', 'N/A', 22, 'SUERO'),
('ESTROGENOS TOTALES', 'ELISA', 'Hormona Femenina', '24 horas', 'N/A', 22, 'SUERO'),
('ENOLASA ESPECIFICA NEURONAL (NSE)', 'ELISA', 'Marcadores Tumorales', '72 horas', 'N/A', 143, 'SUERO'),
('EBV IgG (EPSTEIN BAR)', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 13, 'SUERO'),
('EBV IgM (EPSTEIN BAR)', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 13, 'SUERO'),
('ESPERMATOGRAMA', 'Manual', 'Prueba de Fertilidad', '24 horas', 'N/A', 27, 'SEMEN'),
('ERLICHIA', 'CAPA BLANCA', 'Pruebas Infecciosas', '24 horas', 'N/A', 'VERIFICAR', 'SANGRE TOTAL'),
('ESTRADIOL', 'Quimioluminiscencia', 'Hormona Femenina', '24 horas', '3 horas', 12, 'SUERO'),
('EXAMEN DE HECES', 'Manual', 'Rutina', '24 horas', 'N/A', 4, 'HECES'),
('EXAMEN DE ORINA', 'Manual', 'Rutina', '24 horas', 'N/A', 4, 'ORINA'),
('FACTOR REUMATOIDE', 'Aglutinación', 'Serología', '24 horas', 'N/A', 7, 'SUERO'),
('FACTOR REUMATOIDE IgM', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 31, 'SUERO'),
('FERRITINA', 'Quimioluminiscencia', 'Prueba Especial', '24 horas', '3 horas', 13, 'SUERO'),
('FENOBARBITAL', 'ELISA', 'Prueba Especial', '24 horas', '24 horas', 31, 'SUERO'),
('FENITOINA', 'ELISA', 'Prueba Especial', '24 horas', '24 horas', 31, 'SUERO'),
('FIBRINOGENO', 'Curva', 'Hematología', '24 horas', 'N/A', 6, 'PLASMA CITRATADO'),
('FOSFATASA ALCALINA (ALP)', 'Enzimático', 'Química Sanguínea', '12 horas', 'N/A', 3, 'SUERO'),
('FOSFATASA ACIDA PROSTATICA', 'Colorimetría', 'Prueba Especial', '24 horas', '12 horas', 22, 'SUERO'),
('FOSFORO', 'Colorimetría', 'Química Sanguínea', '24 horas', '12 horas', 3, 'SUERO'),
('FSH', 'Quimioluminiscencia/ELISA', 'Hormona Femenina', '24 horas', '3 horas', 12, 'SUERO'),
('FOLATO', 'ELISA', 'Hormona Femenina', '24 horas', 'N/A', 19, 'SUERO'),
('FTA-ABS', 'Inmunofluorescencia', 'Pruebas Infecciosas', '24 horas', 'N/A', 38, 'SUERO'),
('GGT (Gamma Glutamil Transferasa)', 'Enzimático', 'Química Sanguínea', '12 horas', 'N/A', 3, 'SUERO'),
('GABA ácido gamma-aminobutírico (γ-aminobutírico)', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 143, 'ORINA PARCIAL 2DA ORINA'),
('GALACTOMANANO (ASPERGILUS)', 'FLUJO LATERAL/Quimioluminiscencia', 'Prueba Especial', '48 horas', '12 horas', 99, 'SUERO/LIQUIDO DE LAVADO PULMONAR'),
('GASTRINA (GAS)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 49, 'SUERO'),
('GLICEMIA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('GRUPO SANGUÍNEO', 'Manual', 'Hematología', '24 horas', 'N/A', 6, 'SANGRE TOTAL'),
('H.I.V I y II', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 5, 'SUERO'),
('H.I.V 4TA GENERACION DETECCIÓN ANTIGENO P24', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 16, 'SUERO'),
('HCG CUANTIFICADA (Gonadotrofina Coriónica Humana)', 'Quimioluminiscencia', 'Hormonas Femeninas', '24 horas', '3 horas', 12, 'SUERO'),
('HDL COLESTEROL', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('HELICOBACTER PYLORI IgA', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('HELICOBACTER PYLORI IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('HELICOBACTER PYLORI IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('HELICOBACTER PYLORI EN HECES', 'Test Rápido', 'Pruebas Infecciosas', '12 horas', 'N/A', 16, 'HECES'),
('HEMATOLOGIA COMPLETA CON PLAQUETAS', 'Hematología', 'Hematología', '12 horas', 'N/A', 6, 'SANGRE TOTAL'),
('HEMOGLOBINA GLICOSILADA FRACCION (HbA1c)', 'Colorimetría', 'Prueba Especial', '12 horas', 'N/A', 15, 'SANGRE TOTAL'),
('HEPATITIS A IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 13, 'SUERO'),
('HEPATITIS A IgG', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 13, 'SUERO'),
('HEPATITIS B sAg (Antigeno de Superficie)', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 11, 'SUERO'),
('HEPATITIS C (HCV)', 'Test Rápido', 'Pruebas Infecciosas', '12 horas', 'N/A', 11, 'SUERO'),
('HEPATITIS C (HCV)', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 11, 'SUERO'),
('HERPES I IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 20, 'SUERO'),
('HERPES I IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 20, 'SUERO'),
('HERPES SIMPLE II IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 20, 'SUERO'),
('HERPES SIMPLE II IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 20, 'SUERO'),
('HE4 (MARCADOR TUMORAL)', 'ELISA', 'Marcadores Tumorales', '24 horas', 'N/A', 38, 'SUERO'),
('HIERRO (FE)', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 9, 'SUERO'),
('HISTAMINA', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 99, 'SUERO'),
('HORMONA ANTI-MULLERIANA', 'Quimioluminiscencia', 'Prueba Especial', '24 horas', '3 horas', 49, 'SUERO'),
('HORMONA DE CRECIMIENTO (HGH)', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 20, 'SUERO'),
('HTLV I/II', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 20, 'SUERO'),
('IgA (SERICA)', 'Inmunodisfusión Radial', 'Perfil Autoinmune', '72 horas', 'N/A', 20, 'SUERO'),
('IgA SECRETORA', 'ELISA', 'Perfil Autoinmune', '24 horas', 'N/A', 33, 'SALIVA'),
('IgE TOTAL', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 16, 'SUERO'),
('IGE ESPECIFICA (LECHE HUEVO-HARINA DE TRIGO-SOYA-CHOCOLATE) ENTRE OTROS CONSULTAR LISTA DE ALERGENOS', 'ELISA', 'Prueba Especial', '12 días hábiles', 'N/A', 24, 'SUERO'),
('IGG ESPECIFICA (LECHE-HUEVO-HARINA DE TRIGO-SOYA-CHOCOLATE) ENTRE OTROS CONSULTAR LISTA DE ALERGENOS', 'ELISA', 'Prueba Especial', '12 días hábiles', 'N/A', 24, 'SUERO'),
('IGF-1 (SOMATOMEDINA C)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 54, 'SUERO'),
('IgG (SERICA)', 'Inmunodisfusión Radial', 'Perfil Autoinmune', '72 horas', 'N/A', 20, 'SUERO'),
('IgM (SERICA)', 'Inmunodisfusión Radial', 'Perfil Autoinmune', '72 horas', 'N/A', 20, 'SUERO'),
('IGRA (ENSAYO DE LIBERACIÓN DE INTERFERON GAMMA PARA TUBERCULOSIS)', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 77, 'SANGRE CON HEPARINA'),
('INDICE CALCIO/CREATININA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 14, 'ORINA'),
('INDICE ACIDO URICO/CREATININA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 10, 'ORINA'),
('INDICE FOSFORO/CREATININA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 14, 'ORINA'),
('INDICE MICROALBUMINA/CREATININA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 11, 'ORINA'),
('INDICE HOMA', 'ELISA', 'Prueba Especial', '12 horas', 'N/A', 0, 'SUERO'),
('INTERLEUKINA 6', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 53, 'SUERO'),
('INSULINA', 'Quimioluminiscencia', 'Prueba Especial', '24 horas', '3 horas', 11, 'SUERO'),
('INHIBIDOR C1', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 49, 'SUERO'),
('INFLUENZA A+B', 'Prueba Rápida', 'Prueba Especial', '12 horas', 'N/A', 30, 'HISOPADO MOCO NASAL'),
('INVESTIGACION DE CELULAS DREPANOCÍTICAS', 'Manual', 'Hematología', '24 horas', 'N/A', 13, 'SANGRE TOTAL'),
('LACTATO', 'Enzimático', 'Química Sanguínea', '24 horas', 'N/A', 30, 'PLASMA EDTA'),
('LDH (Lactico Deshidrogenasa)', 'Enzimático', 'Química Sanguínea', '24 horas', 'N/A', 3, 'SUERO'),
('LDL COLESTEROL', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('LEPTOSPIRA IgM-IgG', 'Test Rápido', 'Pruebas Infecciosas', '24 horas', 'N/A', 22, 'SUERO'),
('LH', 'Quimioluminiscencia/ELISA', 'Hormona Femenina', '24 horas', '3 horas', 12, 'SUERO'),
('LIPASA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 12, 'SUERO'),
('MAGNESIO (Mg)', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 3, 'SUERO'),
('MALARIA', 'Test Rápido', 'Pruebas Infecciosas', '12 horas', 'N/A', 10, 'SUERO'),
('METANEFRINA', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 121, 'ORINA 24 HORAS'),
('MICROALBUMINURIA', 'Colorimetría', 'Colorimetría', '24 horas', 'N/A', 9, 'ORINA'),
('MARIHUANA (THC)', 'Test Rápido', 'Toxicología', '12 horas', 'N/A', 7, 'ORINA'),
('MYOGLOBINA', 'Inmunofluorescencia en Placa', 'Prueba Especial', '3 horas', 'N/A', 33, 'SUERO/PLASMA'),
('Mycoplasma Pneumoniae IgG', 'Quimioluminiscencia', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('Mycoplasma Pneumoniae IgM', 'Quimioluminiscencia', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('RENINA', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 99, 'SUERO/PLASMA'),
('OXALATO EN ORINA', 'Colorimetría', 'Metabolismo Renal', '24 horas', 'N/A', 55, 'ORINA'),
('OSMOLARIDAD URINARIA', 'Colorimetría', 'Metabolismo Renal', '24 horas', 'N/A', 30, 'ORINA'),
('PANEL DE ALIMENTOS VENEZUELA 20 ALERGENOS', 'INMUNOBLOT (CUANTITATIVO)', 'Prueba Especial', '24 horas', 'N/A', 70, 'SUERO'),
('PANEL RESPIRATORIO 20 ALERGENOS VENEZOLANO', 'INMUNOBLOT (CUANTITATIVO)', 'Prueba Especial', '24 horas', 'N/A', 70, 'SUERO'),
('PANEL DE ALERGIAS ATOPIC 20 ALERGENOS MIXTOS INHALANTES Y ALIMENTOS', 'INMUNOBLOT CUANTITATIVO', 'Prueba Especial', '24 horas', 'N/A', 75, 'SUERO'),
('PANEL DE ALERGIAS PEDIATRICO 10 ALERGENOS', 'INMUNOBLOT CUANTITATIVO', 'Prueba Especial', '24 horas', 'N/A', 70, 'SUERO'),
('PANEL DE ALERGIAS A MEDICAMENTOS', 'INMUNOBLOT CUANTITATIVO', 'Prueba Especial', '24 horas', 'N/A', 91, 'SUERO'),
('PAPP-A', 'ELISA', 'Cribado Prenatal', '24 horas', 'N/A', 27, 'SUERO'),
('PEPTIDO C', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 16, 'SUERO'),
('PEPSINOGENO I (PGI)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 38, 'SUERO'),
('PEPSINOGENO II (PGI)', 'ELISA', 'Prueba Especial', '24 horas', 'N/A', 38, 'SUERO'),
('PERFIL CELIACO 6 ANTIGENOS', 'INMUNOBLOT', 'Prueba Especial', '24 horas', 'N/A', 79, 'SUERO'),
('PERFIL HEPATITIS AUTOINMUNE 10 ANTIGENOS', 'INMUNOBLOT', 'Prueba Especial', '24 horas', 'N/A', 79, 'SUERO'),
('PERFIL AUTOINMUNE', 'INMUNOBLOT', 'Prueba Especial', '24 horas', 'N/A', 79, 'SUERO'),
('PLOMO EN SANGRE', 'Absorción Atómica', 'Química Sanguínea', '12 días hábiles', 'N/A', 38, 'SANGRE TOTAL'),
('POTASIO (K)', 'Colorimetría', 'Química Sanguínea', '3 horas', 'N/A', 7, 'SUERO/ORINA'),
('PROCALCITONINA', 'Inmunofluorescencia/Quimioluminiscencia', 'Marcador de Sepsis Neonatal', '12 horas', '3 horas', 16, 'SUERO'),
('PROGESTERONA', 'Quimioluminiscencia/ELISA', 'Hormona Femenina', '24 horas', '3 horas', 12, 'SUERO'),
('PROLACTINA (PRL)', 'Quimioluminiscencia/ELISA', 'Química Sanguínea', '24 horas', '3 horas', 12, 'SUERO'),
('PROTEINA C REACTIVA (PCR)', 'Aglutinación', 'Serología', '24 horas', 'N/A', 8, 'SUERO'),
('PCR ULTRASENSIBLE', 'Turbidimetría', 'Serología', '24 horas', 'N/A', 10, 'SUERO'),
('PROTEINAS TOTALES', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('PROTEINURIA', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 18, 'ORINA'),
('PRUEBA DE EMBARAZO EN SANGRE (HCG)', 'Test Rápido', 'Hormona', '3 horas', 'N/A', 7, 'SUERO'),
('PSA LIBRE (Antígeno Prostático Libre)', 'Quimioluminiscencia', 'Marcadores Tumorales', '24 horas', '3 horas', 12, 'SUERO'),
('PSA TOTAL (Antígeno Prostático Total)', 'Quimioluminiscencia', 'Marcadores Tumorales', '24 horas', '3 horas', 12, 'SUERO'),
('PT (Tiempo de Protrombina)', 'Manual', 'Hematología', '12 horas', 'N/A', 9, 'PLASMA CITRATADO'),
('PTT (Tiempo Parcial de Tromboplastina)', 'Manual', 'Hematología', '12 horas', 'N/A', 9, 'PLASMA CITRATADO'),
('PARVOVIRUS B19 IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 53, 'SUERO'),
('PARVOVIRUS B19 IgG', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 53, 'SUERO'),
('PARATOHORMONA (PTH) INTACTA FRACCION 84', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 33, 'SUERO'),
('PAROTIDITIS IgM (MUMPS) IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 35, 'SUERO'),
('PAROTIDITIS IgG (MUMPS) IgG', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 35, 'SUERO'),
('RECUENTO DE EOSINOFILOS', 'Manual', 'Prueba Especial', '24 horas', 'N/A', 6, 'PLASMA EDTA'),
('RUBEOLA IgG', 'Quimioluminiscencia', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('RUBEOLA IgM', 'Quimioluminiscencia', 'Pruebas Infecciosas', '24 horas', '3 horas', 16, 'SUERO'),
('ROTAVIRUS', 'TEST RAPIDO', 'Pruebas Infecciosas', '12 horas', 'N/A', 11, 'SUERO'),
('SARAMPION (MEASLES) IgM', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 33, 'SUERO'),
('SARAMPION (MEASLES) IgG', 'ELISA', 'Pruebas Infecciosas', '24 horas', 'N/A', 33, 'SUERO'),
('SANGRE OCULTA EN HECES', 'Test Rápido', 'Coprología', '12 horas', 'N/A', 9, 'HECES'),
('SANGRE OCULTA EN HECES + TRANSFERRINA', 'Test Rápido', 'Coprología', '12 horas', 'N/A', 18, 'HECES'),
('SEROLOGIA PARA HONGOS', 'Inmunodifusión Radial', 'Serología', '72 horas', 'N/A', 141, 'SUERO'),
('SEROTONINA', 'ELISA', 'Prueba Especial', '72 horas', 'N/A', 95, 'SUERO'),
('SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2 (IgM/IgG)', 'Test Rápido', 'Pruebas Infecciosas', '3 horas', 'N/A', 22, 'SUERO'),
('SHBG (Globulina Fijadora de Hormonas Sexuales)', 'ELISA', 'Prueba Especial', '24 horas', '3 horas', 22, 'SUERO'),
('SIFILIS (ANTICUERPOS ANTI-TREPONEMA IgM+IgG)', 'ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 11, 'SUERO'),
('SODIO (NA)', 'Colorimetría', 'Química Sanguínea', '3 horas', 'N/A', 11, 'SUERO/ORINA'),
('SUDAN III', 'Manual', 'Coprología', '3 horas', 'N/A', 6, 'HECES'),
('T3 LIBRE', 'Quimioluminiscencia/ELISA', 'Hormona Tiroidea', '24 horas', '3 horas', 12, 'SUERO'),
('T3 TOTAL', 'Quimioluminiscencia/ELISA', 'Hormona Tiroidea', '24 horas', '3 horas', 12, 'SUERO'),
('T4 LIBRE', 'Quimioluminiscencia/ELISA', 'Hormona Tiroidea', '24 horas', '3 horas', 12, 'SUERO'),
('T4 TOTAL', 'Quimioluminiscencia/ELISA', 'Hormona Tiroidea', '24 horas', '3 horas', 12, 'SUERO'),
('TESTOSTERONA LIBRE', 'Quimioluminiscencia/ELISA', 'Hormona Masculina', '24 horas', '3 horas', 12, 'SUERO'),
('TESTOSTERONA TOTAL', 'Quimioluminiscencia/ELISA', 'Hormona Masculina', '24 horas', '3 horas', 12, 'SUERO'),
('TIROGLOBULINA', 'ELISA', 'Hormona Tiroidea', '24 horas', 'N/A', 18, 'SUERO'),
('TGO (Transaminasa Glutámico Oxaloacética)', 'Cinético', 'Química Sanguínea', '12 horas', 'N/A', 2.50, 'SUERO'),
('TGP (Transaminasa Glutámico Pirúvica)', 'Cinético', 'Química Sanguínea', '12 horas', 'N/A', 2.50, 'SUERO'),
('TOXOPLASMA IgG', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 11, 'SUERO'),
('TOXOPLASMA AVIDEZ', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 33, 'SUERO'),
('TOXOPLASMA IgM', 'Quimioluminiscencia/ELISA', 'Pruebas Infecciosas', '24 horas', '3 horas', 11, 'SUERO'),
('TRANSFERRINA', 'Colorimetría', 'Química Sanguínea', '72 horas', 'N/A', 13, 'SUERO'),
('TRANSGLUTAMINASA IgA', 'Quimioluminiscencia', 'Perfil Autoinmune', '24 horas', '3 horas', 27, 'SUERO'),
('TRANSGLUTAMINASA IgG', 'Quimioluminiscencia', 'Perfil Autoinmune', '24 horas', '3 horas', 27, 'SUERO'),
('TRIGLICÉRIDOS', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2.50, 'SUERO'),
('TROPONINA CUANTIFICADA', 'Inmunofluorescencia', 'Marcador Cardiaco', '3 horas', 'N/A', 16, 'SUERO'),
('TSH', 'Quimioluminiscencia', 'Hormonas Tiroideas', '24 horas', '3 horas', 12, 'SUERO'),
('TSH ULTRASENSIBLE (4TA GENERACION)', 'ELISA', 'Hormonas Tiroideas', '12 horas', 'N/A', 'VERIFICAR', 'SUERO'),
('V.D.R.L.', 'Aglutinación', 'Serología', '12 horas', 'N/A', 5, 'SUERO'),
('V.S.G (VELOCIDAD DE SEDIMENTACIÓN GLOBULAR)', 'Manual', 'Hematología', '12 horas', 'N/A', 5, 'SANGRE TOTAL'),
('VITAMINA B12', 'ELISA', 'Perfil Ferrocinético', '12 horas', 'N/A', 18, 'SUERO'),
('VIRUS SINCITIAL RESPIRATORIO IgM (RSV)', 'ELISA', 'Pruebas Infecciosas', '12 horas', 'N/A', 41, 'SUERO'),
('VIRUS SINCITIAL RESPIRATORIO IgG (RSV)', 'ELISA', 'Pruebas Infecciosas', '12 horas', 'N/A', 41, 'SUERO'),
('VLDL COLESTEROL', 'Colorimetría', 'Química Sanguínea', '12 horas', 'N/A', 2, 'SUERO'),
('ZINC (ZN)', 'Turbidimetría', 'Prueba Especial', '12 horas', 'N/A', 53, 'SUERO');
