UPDATE public.estudios SET campos_formulario = '{"nombre":"17-Cetosteroides","unidad":"mg/24h","valor_referencial":"Hombres: 8-25 mg/24h, Mujeres: 6-15 mg/24h"}' WHERE nombre = '17-CETOSTEROIDE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"17-OH Progesterona","unidad":"ng/mL","valor_referencial":"Adultos: \u003c2.0 ng/mL"}' WHERE nombre = '17 OH PROGESTERONA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãcido 5-HIAA","unidad":"mg/24h","valor_referencial":"2-9 mg/24h"}' WHERE nombre = '(5-HIAA) ACIDO 5 HIDROXIINDOLACETICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"25-OH Vitamina D","unidad":"ng/mL","valor_referencial":"Suficiente: 30-100 ng/mL"}' WHERE nombre = '25 OH VITAMINA D';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ACTH","unidad":"pg/mL","valor_referencial":"10-60 pg/mL"}' WHERE nombre = 'ACTH';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Lactato","unidad":"mmol/L","valor_referencial":"0.5-2.2 mmol/L"}' WHERE nombre = 'ACIDO LACTICO (LACTATO)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãcido VanilmandÃ©lico","unidad":"mg/24h","valor_referencial":"2-7 mg/24h"}' WHERE nombre = 'ACIDO VANILMANDELICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãcido Valproico","unidad":"Î¼g/mL","valor_referencial":"TerapÃ©utico: 50-100 Î¼g/mL"}' WHERE nombre = 'ACIDO VALPROICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ADA","unidad":"U/L","valor_referencial":"LÃ­quido pleural: \u003e30 U/L (sugestivo TB)"}' WHERE nombre = 'ADA (ADENOSINA DEAMINASA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Alfa-1 Antitripsina","unidad":"mg/dL","valor_referencial":"90-200 mg/dL"}' WHERE nombre = 'ALFA 1 ANTITRIPSINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Aspergillus IgG","unidad":"UA/mL","valor_referencial":"\u003c0.35 UA/mL"}' WHERE nombre = 'ASPERGILLUS IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AntÃ­geno SARS-CoV-2","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'ANTIGENO VIRAL PARA SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"COVID-19","unidad":"","valor_referencial":"Negativo"},{"nombre":"Influenza A","unidad":"","valor_referencial":"Negativo"},{"nombre":"Influenza B","unidad":"","valor_referencial":"Negativo"},{"nombre":"RSV","unidad":"","valor_referencial":"Negativo"},{"nombre":"Mycoplasma","unidad":"","valor_referencial":"Negativo"}]' WHERE nombre = 'ANTIGENOS PARA VIRUS Y BACTERIAS RESPIRATORIAS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-MCV","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANTI-MCV (La Vimentina Citrulinada Mutada)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AntÃ­geno SARS-CoV-2 Saliva","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'ANTIGENO VIRAL PARA SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2 EN SALIVA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anticuerpos Neutralizantes","unidad":"%","valor_referencial":"\u003e50% (Protectivo)"}' WHERE nombre = 'ANTICUERPOS NEUTRALIZANTES CONTRA COVID-19';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Aldosterona","unidad":"ng/dL","valor_referencial":"Suero: 4-31 ng/dL"}' WHERE nombre = 'ALDOSTERONA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anaplasma","unidad":"","valor_referencial":"Ausente"}' WHERE nombre = 'ANAPLASMA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anion Gap","unidad":"mEq/L","valor_referencial":"8-16 mEq/L"}' WHERE nombre = 'ANION GAP';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ANCA c (Anti-PR3)","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANCA C (ANTI PR3)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ANCA p (Anti-MPO)","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANCA P (ANTI-MPO)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"RSV AntÃ­geno","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'ANTIGENO DEL VIRUS SINCITIAL RESPIRATORIO (RSV)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ANA PatrÃ³n","unidad":"TÃ­tulo","valor_referencial":"\u003c1:80 (Negativo)"}' WHERE nombre = 'ANTICUERPOS ANTI NUCLEARES ANA PATRON (HEP2)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EMA IgA","unidad":"TÃ­tulo","valor_referencial":"\u003c1:5 (Negativo)"}' WHERE nombre = 'ANTICUERPOS ANTI-ENDOMISIALES (EMA) IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EMA IgG","unidad":"TÃ­tulo","valor_referencial":"\u003c1:5 (Negativo)"}' WHERE nombre = 'ANTICUERPOS ANTI-ENDOMISIALES (EMA) IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AMA","unidad":"TÃ­tulo","valor_referencial":"\u003c1:40 (Negativo)"}' WHERE nombre = 'ANTICUERPOS ANTI-MITOCONDRIALES (AMA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SARS-CoV-2 IgM","unidad":"Ãndice","valor_referencial":"\u003c1.4 (Negativo)"}' WHERE nombre = 'ANTICUERPO SARS-CoV 2 IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SARS-CoV-2 IgA","unidad":"Ãndice","valor_referencial":"\u003c1.4 (Negativo)"}' WHERE nombre = 'ANTICUERPO SARS-CoV 2 IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SARS-CoV-2 IgG","unidad":"AU/mL","valor_referencial":"\u003c50 AU/mL (Negativo)"}' WHERE nombre = 'ANTICUERPO SARS-CoV 2 IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Androstenediona","unidad":"ng/mL","valor_referencial":"Mujeres: 0.3-3.3 ng/mL, Hombres: 0.6-2.7 ng/mL"}' WHERE nombre = 'ANDROSTENEDIONA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Salmonella O","unidad":"TÃ­tulo","valor_referencial":"\u003c1:80"},{"nombre":"Salmonella H","unidad":"TÃ­tulo","valor_referencial":"\u003c1:80"},{"nombre":"Paratyphi A","unidad":"TÃ­tulo","valor_referencial":"\u003c1:80"},{"nombre":"Paratyphi B","unidad":"TÃ­tulo","valor_referencial":"\u003c1:80"}]' WHERE nombre = 'ANTIGENOS FEBRILES (REACCION DE WIDAL)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ASTO","unidad":"UI/mL","valor_referencial":"Adultos: \u003c200 UI/mL, NiÃ±os: \u003c150 UI/mL"}' WHERE nombre = 'A.S.T.O';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãcido Ãšrico","unidad":"mg/dL","valor_referencial":"Hombres: 3.5-7.2 mg/dL, Mujeres: 2.5-6.0 mg/dL"}' WHERE nombre = 'ACIDO URICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AlbÃºmina","unidad":"g/dL","valor_referencial":"3.5-5.0 g/dL"}' WHERE nombre = 'ALBUMINA EN SUERO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AFP","unidad":"ng/mL","valor_referencial":"\u003c10 ng/mL"}' WHERE nombre = 'ALFA-FETOPROTEÃNA (AFP)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Amilasa","unidad":"U/L","valor_referencial":"30-110 U/L"}' WHERE nombre = 'AMILASA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Amonio","unidad":"Î¼mol/L","valor_referencial":"11-32 Î¼mol/L"}' WHERE nombre = 'AMONIO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ANA Screen","unidad":"Ãndice","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'ANA SCREEN IgG';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"SS-A52","unidad":"","valor_referencial":"Negativo"},{"nombre":"JO-1","unidad":"","valor_referencial":"Negativo"},{"nombre":"SM","unidad":"","valor_referencial":"Negativo"},{"nombre":"CENP-B","unidad":"","valor_referencial":"Negativo"},{"nombre":"Histona","unidad":"","valor_referencial":"Negativo"},{"nombre":"SCL-70","unidad":"","valor_referencial":"Negativo"},{"nombre":"U1-SNRNP","unidad":"","valor_referencial":"Negativo"},{"nombre":"SS-A60","unidad":"","valor_referencial":"Negativo"},{"nombre":"MI-2","unidad":"","valor_referencial":"Negativo"},{"nombre":"KU","unidad":"","valor_referencial":"Negativo"}]' WHERE nombre = 'ANA WESTERN BLOT 14 ANTIGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti Jo-1","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI JO-1';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Î²2 GlicoproteÃ­na IgG","unidad":"GPL","valor_referencial":"\u003c20 GPL"}' WHERE nombre = 'ANTI-BETA 2 GLYCOPROTEINA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Beta-2 Microglobulina","unidad":"mg/L","valor_referencial":"0.8-2.2 mg/L"}' WHERE nombre = 'ANTI-BETA 2 MICROGLOBULINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-CCP","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANTI-CCP';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Sm","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI-SM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-SSA/Ro","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI-SSA (RO)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-SSB/La","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI-SSB (LA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Î²2 GlicoproteÃ­na IgM","unidad":"MPL","valor_referencial":"\u003c20 MPL"}' WHERE nombre = 'ANTI-BETA 2 GLYCOPROTEINA IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anticardiolipina IgM","unidad":"MPL","valor_referencial":"\u003c20 MPL"}' WHERE nombre = 'ANTI-CARDIOLIPINA IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anticardiolipina IgG","unidad":"GPL","valor_referencial":"\u003c20 GPL"}' WHERE nombre = 'ANTI-CARDIOLIPINA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AntifosfolÃ­pidos IgM","unidad":"MPL","valor_referencial":"\u003c20 MPL"}' WHERE nombre = 'ANTI-FOSFOLIPIDOS IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AntifosfolÃ­pidos IgG","unidad":"GPL","valor_referencial":"\u003c20 GPL"}' WHERE nombre = 'ANTI-FOSFOLIPIDOS IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anticoagulante LÃºpico","unidad":"Ratio","valor_referencial":"\u003c1.2 (Negativo)"}' WHERE nombre = 'ANTICOAGULANTE LUPICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-HBe","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'ANTICUERPO CONTRA EL ANTIGENO DE SUPERFICIE DE LA HEPATITIS E (HBeAb)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-dsDNA","unidad":"UI/mL","valor_referencial":"\u003c30 UI/mL"}' WHERE nombre = 'ANTI-DS DNA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CEA","unidad":"ng/mL","valor_referencial":"No fumadores: \u003c5 ng/mL, Fumadores: \u003c10 ng/mL"}' WHERE nombre = 'ANTIGENO CARCINOEMBRIONARIO (C.E.A)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HBsAg","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'ANTIGENO DE SUPERFICIE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HBeAg","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'ANTIGENO DE SUPERFICIE DE LA HEPATITIS E (HBeAg)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Gliadina Deaminada IgA","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANTI-GLIADINA DEAMINADA IgA GLIADINA SEGUNDA GENERACION';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Gliadina Deaminada IgG","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'ANTI-GLIADINA DEAMINADA IgG GLIADINA SEGUNDA GENERACION';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Scl-70","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI-SCL-70';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-LKM1","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ANTI-LKM1';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Tiroglobulina","unidad":"UI/mL","valor_referencial":"\u003c115 UI/mL"}' WHERE nombre = 'ANTI-TIROGLOBULINA (ANTI-TG)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-TPO","unidad":"UI/mL","valor_referencial":"\u003c34 UI/mL"}' WHERE nombre = 'ANTI-TIROPEROXIDASA (ANTI-TPO)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ASCA IgA","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ASCA IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ASCA IgG","unidad":"U/mL","valor_referencial":"\u003c25 U/mL"}' WHERE nombre = 'ASCA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AzÃºcares Reductores","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'AZUCARES REDUCTORES';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Beta hCG","unidad":"mIU/mL","valor_referencial":"No embarazada: \u003c5 mIU/mL"}' WHERE nombre = 'Beta hCG (BhCG)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Bilirrubina Total","unidad":"mg/dL","valor_referencial":"0.3-1.2 mg/dL"},{"nombre":"Bilirrubina Directa","unidad":"mg/dL","valor_referencial":"0.1-0.4 mg/dL"},{"nombre":"Bilirrubina Indirecta","unidad":"mg/dL","valor_referencial":"0.2-0.8 mg/dL"}]' WHERE nombre = 'BILIRRUBINA TOTAL Y FRACCIONADA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Bordetella IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'BORDETELLA IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Urea","unidad":"mg/dL","valor_referencial":"7-25 mg/dL"}' WHERE nombre = 'BUN (UREA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Citograma Nasal","unidad":"","valor_referencial":"CÃ©lulas epiteliales normales"}' WHERE nombre = 'CITOGRAMA EN MOCO NASAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Coombs Directo","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'COOMBS DIRECTO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Coombs Indirecto","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'COOMBS INDIRECTO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Fragilidad OsmÃ³tica","unidad":"%","valor_referencial":"Inicio: 0.45-0.35%, Completa: 0.35-0.30%"}' WHERE nombre = 'CURVA DE FRAGILIDAD OSMOTICA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Dopamina","unidad":"Î¼g/24h","valor_referencial":"65-400 Î¼g/24h"},{"nombre":"Adrenalina","unidad":"Î¼g/24h","valor_referencial":"0-20 Î¼g/24h"},{"nombre":"Noradrenalina","unidad":"Î¼g/24h","valor_referencial":"15-80 Î¼g/24h"}]' WHERE nombre = 'CATECOLAMINAS EN ORINA (DOPAMINA, ADRENALINA, NORADRENALINA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Calcitonina","unidad":"pg/mL","valor_referencial":"Hombres: \u003c11.5 pg/mL, Mujeres: \u003c4.6 pg/mL"}' WHERE nombre = 'CALCITONINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CA 125","unidad":"U/mL","valor_referencial":"\u003c35 U/mL"}' WHERE nombre = 'CA 125';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CA 15-3","unidad":"U/mL","valor_referencial":"\u003c30 U/mL"}' WHERE nombre = 'CA 15-3';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CA 72-4","unidad":"U/mL","valor_referencial":"\u003c6.9 U/mL"}' WHERE nombre = 'CA 72-4';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CA 19-9","unidad":"U/mL","valor_referencial":"\u003c40 U/mL"}' WHERE nombre = 'CA 19-9';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Calprotectina","unidad":"Î¼g/g","valor_referencial":"\u003c50 Î¼g/g"}' WHERE nombre = 'CALPROTECTINA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Cadenas Ligeras Kappa","unidad":"mg/L","valor_referencial":"3.3-19.4 mg/L"},{"nombre":"Cadenas Ligeras Lambda","unidad":"mg/L","valor_referencial":"5.7-26.3 mg/L"}]' WHERE nombre = 'CADENAS LIGERAS KAPPA Y LAMBDA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Calcio","unidad":"mg/dL","valor_referencial":"8.5-10.2 mg/dL"}' WHERE nombre = 'CALCIO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Calcio IÃ³nico","unidad":"mg/dL","valor_referencial":"4.5-5.6 mg/dL"}' WHERE nombre = 'CALCIO IONICO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AnÃ¡lisis de CÃ¡lculo","unidad":"","valor_referencial":"ComposiciÃ³n quÃ­mica identificada"}' WHERE nombre = 'CALCULOS URINARIOS Y CRISTALES URINARIOS (CALCIO, MAGNESIO, OXALATO, AMONIO, FOSFATO, CISTINA, ACIDO URICO)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Carbamazepina","unidad":"Î¼g/mL","valor_referencial":"TerapÃ©utico: 4-12 Î¼g/mL"}' WHERE nombre = 'CARBAMAZEPINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CÃ©lulas NK","unidad":"cÃ©lulas/Î¼L","valor_referencial":"90-600 cÃ©lulas/Î¼L"}' WHERE nombre = 'CELULAS NK Y NKT';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"CD3+","unidad":"%","valor_referencial":"55-83%"},{"nombre":"CD4+","unidad":"cÃ©lulas/Î¼L","valor_referencial":"500-1600 cÃ©lulas/Î¼L"},{"nombre":"CD8+","unidad":"cÃ©lulas/Î¼L","valor_referencial":"200-1200 cÃ©lulas/Î¼L"}]' WHERE nombre = 'CD3+CD4+CD8 (DETECCION CELULAR)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CÃ©lulas LE","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'CELULAS LE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Cistatina C","unidad":"mg/L","valor_referencial":"0.5-0.96 mg/L"}' WHERE nombre = 'CISTATINA C';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CH50","unidad":"U/mL","valor_referencial":"150-250 U/mL"}' WHERE nombre = 'CH 50';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Chagas","unidad":"Ãndice","valor_referencial":"\u003c1.0 (No reactivo)"}' WHERE nombre = 'CHAGAS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"C. Pneumoniae IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Chlamydia Pneumoniae IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"C. Pneumoniae IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Chlamydia Pneumoniae IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"C. Trachomatis IgA","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Chlamydia Trachomatis IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"C. Trachomatis IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Chlamydia Trachomatis IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"C. Trachomatis IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Chlamydia Trachomatis IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AnÃ¡lisis CitoquÃ­mico","unidad":"","valor_referencial":"SegÃºn tipo de lÃ­quido"}' WHERE nombre = 'CITOQUIMICOS DE LIQUIDOS: (CEFALORRAQUIDEO, PLEURAL, SINOVIAL, PERICARDICO, ASITICO, PERITONEAL)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Citrato","unidad":"mg/24h","valor_referencial":"320-1240 mg/24h"}' WHERE nombre = 'CITRATO EN ORINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CTX-1","unidad":"ng/mL","valor_referencial":"Mujeres premenopaÃºsicas: \u003c0.573 ng/mL"}' WHERE nombre = 'CTX-1 (Telopeptido C del Colageno tipo I)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Creatina Kinasa","unidad":"U/L","valor_referencial":"Hombres: 38-174 U/L, Mujeres: 26-140 U/L"}' WHERE nombre = 'CK';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CK-MB","unidad":"ng/mL","valor_referencial":"\u003c6.3 ng/mL"}' WHERE nombre = 'CK-MB';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Cloro","unidad":"mEq/L","valor_referencial":"96-106 mEq/L"}' WHERE nombre = 'CLORO (CL)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CMV IgG","unidad":"UA/mL","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'CMV IgG (Cytomegalovirus)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CMV IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'CMV IgM (Cytomegalovirus)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Cobre","unidad":"Î¼g/dL","valor_referencial":"70-140 Î¼g/dL"}' WHERE nombre = 'COBRE (Cu)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"CocaÃ­na","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'COCAINA EN ORINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Colesterol Total","unidad":"mg/dL","valor_referencial":"\u003c200 mg/dL"}' WHERE nombre = 'COLESTEROL TOTAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Colinesterasa","unidad":"U/L","valor_referencial":"5320-12920 U/L"}' WHERE nombre = 'COLINESTERASA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Complemento C3","unidad":"mg/dL","valor_referencial":"90-180 mg/dL"}' WHERE nombre = 'COMPLEMENTO C3';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Complemento C4","unidad":"mg/dL","valor_referencial":"10-40 mg/dL"}' WHERE nombre = 'COMPLEMENTO C4';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Reticulocitos","unidad":"%","valor_referencial":"0.5-2.5%"}' WHERE nombre = 'CONTAJE DE RETICULOCITOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-HBc IgM","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'CORE IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-HBc Total","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'CORE IgM + IgG (ANTICUERPOS TOTALES)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Cortisol","unidad":"Î¼g/dL","valor_referencial":"AM: 5-25 Î¼g/dL, PM: 3-12 Î¼g/dL"}' WHERE nombre = 'CORTISOL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Creatinina","unidad":"mg/dL","valor_referencial":"Hombres: 0.7-1.3 mg/dL, Mujeres: 0.6-1.2 mg/dL"}' WHERE nombre = 'CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Cromogranina A","unidad":"ng/mL","valor_referencial":"\u003c93 ng/mL"}' WHERE nombre = 'CROMOGRANINA A';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Digoxina","unidad":"ng/mL","valor_referencial":"TerapÃ©utico: 0.8-2.0 ng/mL"}' WHERE nombre = 'DIGOXINA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Dengue IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"Dengue IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}]' WHERE nombre = 'DENGUE IgM-IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Dengue IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'DENGUE IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Dengue IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'DENGUE IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"DepuraciÃ³n de Creatinina","unidad":"mL/min/1.73mÂ²","valor_referencial":"\u003e90 mL/min/1.73mÂ²"}' WHERE nombre = 'DEPURACION DE CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"DepuraciÃ³n de Urea","unidad":"mL/min","valor_referencial":"64-99 mL/min"}' WHERE nombre = 'DEPURACION DE UREA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Dihidrotestosterona","unidad":"ng/dL","valor_referencial":"Hombres: 30-85 ng/dL"}' WHERE nombre = 'DIHIDROTESTOSTERONA (DHT)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel Disbiosis","unidad":"","valor_referencial":"SegÃºn parÃ¡metros individuales"}' WHERE nombre = 'DISBIOSIS INTESTINAL (Examen de Heces+ Helicobacter Pylori en Heces + Calprotectina+ IgA Secretora+ Zonulina)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"DÃ­mero D","unidad":"ng/mL","valor_referencial":"\u003c500 ng/mL"}' WHERE nombre = 'DIMERO D';
UPDATE public.estudios SET campos_formulario = '{"nombre":"DHEA-S","unidad":"Î¼g/dL","valor_referencial":"Mujeres: 35-430 Î¼g/dL, Hombres: 80-560 Î¼g/dL"}' WHERE nombre = 'DHEA-S';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Estriol Libre","unidad":"ng/mL","valor_referencial":"SegÃºn edad gestacional"}' WHERE nombre = 'ESTRIOL LIBRE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EstrÃ³genos Totales","unidad":"pg/mL","valor_referencial":"Fase folicular: 60-200 pg/mL"}' WHERE nombre = 'ESTROGENOS TOTALES';
UPDATE public.estudios SET campos_formulario = '{"nombre":"NSE","unidad":"ng/mL","valor_referencial":"\u003c16.3 ng/mL"}' WHERE nombre = 'ENOLASA ESPECIFICA NEURONAL (NSE)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EBV IgG","unidad":"UA/mL","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'EBV IgG (EPSTEIN BAR)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EBV IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'EBV IgM (EPSTEIN BAR)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"ConcentraciÃ³n","unidad":"millones/mL","valor_referencial":"\u003e15 millones/mL"},{"nombre":"Movilidad","unidad":"%","valor_referencial":"\u003e40%"},{"nombre":"MorfologÃ­a","unidad":"%","valor_referencial":"\u003e4% formas normales"}]' WHERE nombre = 'ESPERMATOGRAMA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Erlichia","unidad":"","valor_referencial":"Ausente"}' WHERE nombre = 'ERLICHIA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Estradiol","unidad":"pg/mL","valor_referencial":"Fase folicular: 30-120 pg/mL"}' WHERE nombre = 'ESTRADIOL';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Consistencia","unidad":"","valor_referencial":"Formadas"},{"nombre":"Color","unidad":"","valor_referencial":"MarrÃ³n"},{"nombre":"ParÃ¡sitos","unidad":"","valor_referencial":"Ausentes"},{"nombre":"Leucocitos","unidad":"x campo","valor_referencial":"\u003c10 x campo"}]' WHERE nombre = 'EXAMEN DE HECES';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Densidad","unidad":"","valor_referencial":"1.003-1.030"},{"nombre":"pH","unidad":"","valor_referencial":"5.0-8.0"},{"nombre":"ProteÃ­nas","unidad":"mg/dL","valor_referencial":"Negativo"},{"nombre":"Glucosa","unidad":"mg/dL","valor_referencial":"Negativo"},{"nombre":"Leucocitos","unidad":"x campo","valor_referencial":"\u003c10 x campo"},{"nombre":"Eritrocitos","unidad":"x campo","valor_referencial":"\u003c5 x campo"}]' WHERE nombre = 'EXAMEN DE ORINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Factor Reumatoide","unidad":"UI/mL","valor_referencial":"\u003c14 UI/mL"}' WHERE nombre = 'FACTOR REUMATOIDE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Factor Reumatoide IgM","unidad":"UI/mL","valor_referencial":"\u003c20 UI/mL"}' WHERE nombre = 'FACTOR REUMATOIDE IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ferritina","unidad":"ng/mL","valor_referencial":"Hombres: 12-300 ng/mL, Mujeres: 12-150 ng/mL"}' WHERE nombre = 'FERRITINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Fenobarbital","unidad":"Î¼g/mL","valor_referencial":"TerapÃ©utico: 15-40 Î¼g/mL"}' WHERE nombre = 'FENOBARBITAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"FenitoÃ­na","unidad":"Î¼g/mL","valor_referencial":"TerapÃ©utico: 10-20 Î¼g/mL"}' WHERE nombre = 'FENITOINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"FibrinÃ³geno","unidad":"mg/dL","valor_referencial":"200-400 mg/dL"}' WHERE nombre = 'FIBRINOGENO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Fosfatasa Alcalina","unidad":"U/L","valor_referencial":"44-147 U/L"}' WHERE nombre = 'FOSFATASA ALCALINA (ALP)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Fosfatasa Ãcida ProstÃ¡tica","unidad":"ng/mL","valor_referencial":"\u003c3.0 ng/mL"}' WHERE nombre = 'FOSFATASA ACIDA PROSTATICA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"FÃ³sforo","unidad":"mg/dL","valor_referencial":"2.5-4.5 mg/dL"}' WHERE nombre = 'FOSFORO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"FSH","unidad":"mIU/mL","valor_referencial":"Mujeres fase folicular: 3-10 mIU/mL, Hombres: 1.5-12.4 mIU/mL"}' WHERE nombre = 'FSH';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Folato","unidad":"ng/mL","valor_referencial":"2.7-17.0 ng/mL"}' WHERE nombre = 'FOLATO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"FTA-ABS","unidad":"","valor_referencial":"No reactivo"}' WHERE nombre = 'FTA-ABS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"GGT","unidad":"U/L","valor_referencial":"5-80 U/L"}' WHERE nombre = 'GGT (Gamma Glutamil Transferasa)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"GABA","unidad":"Î¼mol/L","valor_referencial":"0.5-3.0 Î¼mol/L"}' WHERE nombre = 'GABA Ã¡cido gamma-aminobutÃ­rico (Î³-aminobutÃ­rico)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Galactomanano","unidad":"Ãndice","valor_referencial":"\u003c0.5 (Negativo)"}' WHERE nombre = 'GALACTOMANANO (ASPERGILUS)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Gastrina","unidad":"pg/mL","valor_referencial":"\u003c100 pg/mL"}' WHERE nombre = 'GASTRINA (GAS)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Glucosa","unidad":"mg/dL","valor_referencial":"70-100 mg/dL"}' WHERE nombre = 'GLICEMIA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Grupo ABO","unidad":"","valor_referencial":"A, B, AB, O"},{"nombre":"Factor Rh","unidad":"","valor_referencial":"Positivo/Negativo"}]' WHERE nombre = 'GRUPO SANGUÃNEO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HIV 1+2","unidad":"S/CO","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'H.I.V I y II';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HIV Ag/Ab","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'H.I.V 4TA GENERACION DETECCIÃ“N ANTIGENO P24';
UPDATE public.estudios SET campos_formulario = '{"nombre":"hCG Cuantitativa","unidad":"mIU/mL","valor_referencial":"No embarazada: \u003c5 mIU/mL"}' WHERE nombre = 'HCG CUANTIFICADA (Gonadotrofina CoriÃ³nica Humana)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HDL Colesterol","unidad":"mg/dL","valor_referencial":"Hombres: \u003e40 mg/dL, Mujeres: \u003e50 mg/dL"}' WHERE nombre = 'HDL COLESTEROL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"H. Pylori IgA","unidad":"UA/mL","valor_referencial":"\u003c20 UA/mL (Negativo)"}' WHERE nombre = 'HELICOBACTER PYLORI IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"H. Pylori IgG","unidad":"UA/mL","valor_referencial":"\u003c20 UA/mL (Negativo)"}' WHERE nombre = 'HELICOBACTER PYLORI IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"H. Pylori IgM","unidad":"UA/mL","valor_referencial":"\u003c20 UA/mL (Negativo)"}' WHERE nombre = 'HELICOBACTER PYLORI IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"H. Pylori AntÃ­geno","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'HELICOBACTER PYLORI EN HECES';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Hemoglobina","unidad":"g/dL","valor_referencial":"Hombres: 13.5-17.5 g/dL, Mujeres: 12-16 g/dL"},{"nombre":"Hematocrito","unidad":"%","valor_referencial":"Hombres: 41-53%, Mujeres: 36-46%"},{"nombre":"Eritrocitos","unidad":"mill/Î¼L","valor_referencial":"Hombres: 4.5-5.9, Mujeres: 4.1-5.1"},{"nombre":"Leucocitos","unidad":"/Î¼L","valor_referencial":"4,000-11,000/Î¼L"},{"nombre":"Plaquetas","unidad":"/Î¼L","valor_referencial":"150,000-450,000/Î¼L"},{"nombre":"VCM","unidad":"fL","valor_referencial":"80-100 fL"},{"nombre":"HCM","unidad":"pg","valor_referencial":"27-33 pg"},{"nombre":"CHCM","unidad":"g/dL","valor_referencial":"32-36 g/dL"},{"nombre":"NeutrÃ³filos","unidad":"%","valor_referencial":"55-70%"},{"nombre":"Linfocitos","unidad":"%","valor_referencial":"20-40%"},{"nombre":"Monocitos","unidad":"%","valor_referencial":"2-8%"},{"nombre":"EosinÃ³filos","unidad":"%","valor_referencial":"1-4%"},{"nombre":"BasÃ³filos","unidad":"%","valor_referencial":"0-1%"}]' WHERE nombre = 'HEMATOLOGIA COMPLETA CON PLAQUETAS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HbA1c","unidad":"%","valor_referencial":"\u003c5.7% (Normal), 5.7-6.4% (Prediabetes), â‰¥6.5% (Diabetes)"}' WHERE nombre = 'HEMOGLOBINA GLICOSILADA FRACCION (HbA1c)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Hepatitis A IgM","unidad":"S/CO","valor_referencial":"\u003c0.8 (Negativo)"}' WHERE nombre = 'HEPATITIS A IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Hepatitis A IgG","unidad":"mIU/mL","valor_referencial":"\u003c20 (Negativo)"}' WHERE nombre = 'HEPATITIS A IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HBsAg","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'HEPATITIS B sAg (Antigeno de Superficie)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-HCV","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'HEPATITIS C (HCV)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-HCV","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'HEPATITIS C (HCV)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Herpes I IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'HERPES I IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Herpes I IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'HERPES I IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Herpes II IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'HERPES SIMPLE II IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Herpes II IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'HERPES SIMPLE II IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HE4","unidad":"pmol/L","valor_referencial":"PremenopaÃºsica: \u003c70 pmol/L, PostmenopaÃºsica: \u003c140 pmol/L"}' WHERE nombre = 'HE4 (MARCADOR TUMORAL)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Hierro","unidad":"Î¼g/dL","valor_referencial":"60-170 Î¼g/dL"}' WHERE nombre = 'HIERRO (FE)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Histamina","unidad":"ng/mL","valor_referencial":"\u003c1.0 ng/mL"}' WHERE nombre = 'HISTAMINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AMH","unidad":"ng/mL","valor_referencial":"1.0-8.0 ng/mL"}' WHERE nombre = 'HORMONA ANTI-MULLERIANA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Hormona de Crecimiento","unidad":"ng/mL","valor_referencial":"\u003c10 ng/mL"}' WHERE nombre = 'HORMONA DE CRECIMIENTO (HGH)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HTLV I/II","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'HTLV I/II';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgA","unidad":"mg/dL","valor_referencial":"70-400 mg/dL"}' WHERE nombre = 'IgA (SERICA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgA Secretora","unidad":"mg/dL","valor_referencial":"5-25 mg/dL"}' WHERE nombre = 'IgA SECRETORA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgE Total","unidad":"UI/mL","valor_referencial":"\u003c100 UI/mL"}' WHERE nombre = 'IgE TOTAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgE EspecÃ­fica","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L (Negativo)"}' WHERE nombre = 'IGE ESPECIFICA (LECHE HUEVO-HARINA DE TRIGO-SOYA-CHOCOLATE) ENTRE OTROS CONSULTAR LISTA DE ALERGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgG EspecÃ­fica","unidad":"mg/L","valor_referencial":"SegÃºn alergeno"}' WHERE nombre = 'IGG ESPECIFICA (LECHE-HUEVO-HARINA DE TRIGO-SOYA-CHOCOLATE) ENTRE OTROS CONSULTAR LISTA DE ALERGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IGF-1","unidad":"ng/mL","valor_referencial":"SegÃºn edad: 115-400 ng/mL"}' WHERE nombre = 'IGF-1 (SOMATOMEDINA C)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgG","unidad":"mg/dL","valor_referencial":"700-1600 mg/dL"}' WHERE nombre = 'IgG (SERICA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IgM","unidad":"mg/dL","valor_referencial":"40-230 mg/dL"}' WHERE nombre = 'IgM (SERICA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IGRA","unidad":"UI/mL","valor_referencial":"\u003c0.35 UI/mL (Negativo)"}' WHERE nombre = 'IGRA (ENSAYO DE LIBERACIÃ“N DE INTERFERON GAMMA PARA TUBERCULOSIS)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãndice Ca/Cr","unidad":"mg/mg","valor_referencial":"\u003c0.20 mg/mg"}' WHERE nombre = 'INDICE CALCIO/CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãndice AU/Cr","unidad":"mg/mg","valor_referencial":"\u003c0.60 mg/mg"}' WHERE nombre = 'INDICE ACIDO URICO/CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãndice P/Cr","unidad":"mg/mg","valor_referencial":"\u003c0.80 mg/mg"}' WHERE nombre = 'INDICE FOSFORO/CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Ãndice MA/Cr","unidad":"mg/g","valor_referencial":"\u003c30 mg/g"}' WHERE nombre = 'INDICE MICROALBUMINA/CREATININA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"HOMA-IR","unidad":"","valor_referencial":"\u003c2.5"}' WHERE nombre = 'INDICE HOMA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"IL-6","unidad":"pg/mL","valor_referencial":"\u003c7.0 pg/mL"}' WHERE nombre = 'INTERLEUKINA 6';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Insulina","unidad":"Î¼U/mL","valor_referencial":"2.6-24.9 Î¼U/mL"}' WHERE nombre = 'INSULINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Inhibidor C1","unidad":"mg/dL","valor_referencial":"21-39 mg/dL"}' WHERE nombre = 'INHIBIDOR C1';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Influenza A","unidad":"","valor_referencial":"Negativo"},{"nombre":"Influenza B","unidad":"","valor_referencial":"Negativo"}]' WHERE nombre = 'INFLUENZA A+B';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Test Drepanocitos","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'INVESTIGACION DE CELULAS DREPANOCÃTICAS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Lactato","unidad":"mmol/L","valor_referencial":"0.5-2.2 mmol/L"}' WHERE nombre = 'LACTATO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"LDH","unidad":"U/L","valor_referencial":"140-280 U/L"}' WHERE nombre = 'LDH (Lactico Deshidrogenasa)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"LDL Colesterol","unidad":"mg/dL","valor_referencial":"\u003c100 mg/dL"}' WHERE nombre = 'LDL COLESTEROL';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Leptospira IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"Leptospira IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}]' WHERE nombre = 'LEPTOSPIRA IgM-IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"LH","unidad":"mIU/mL","valor_referencial":"Mujeres: 2-10 mIU/mL, Hombres: 1.8-9 mIU/mL"}' WHERE nombre = 'LH';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Lipasa","unidad":"U/L","valor_referencial":"10-60 U/L"}' WHERE nombre = 'LIPASA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Magnesio","unidad":"mg/dL","valor_referencial":"1.7-2.2 mg/dL"}' WHERE nombre = 'MAGNESIO (Mg)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Malaria","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'MALARIA';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Metanefrina","unidad":"Î¼g/24h","valor_referencial":"\u003c400 Î¼g/24h"},{"nombre":"Normetanefrina","unidad":"Î¼g/24h","valor_referencial":"\u003c900 Î¼g/24h"}]' WHERE nombre = 'METANEFRINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"MicroalbÃºmina","unidad":"mg/L","valor_referencial":"\u003c30 mg/L"}' WHERE nombre = 'MICROALBUMINURIA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"THC","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'MARIHUANA (THC)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Mioglobina","unidad":"ng/mL","valor_referencial":"\u003c107 ng/mL"}' WHERE nombre = 'MYOGLOBINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"M. Pneumoniae IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Mycoplasma Pneumoniae IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"M. Pneumoniae IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'Mycoplasma Pneumoniae IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Renina","unidad":"ng/mL/h","valor_referencial":"0.6-4.3 ng/mL/h"}' WHERE nombre = 'RENINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Oxalato","unidad":"mg/24h","valor_referencial":"\u003c40 mg/24h"}' WHERE nombre = 'OXALATO EN ORINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Osmolaridad","unidad":"mOsm/kg","valor_referencial":"300-900 mOsm/kg"}' WHERE nombre = 'OSMOLARIDAD URINARIA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel Alimentos","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L por alÃ©rgeno"}' WHERE nombre = 'PANEL DE ALIMENTOS VENEZUELA 20 ALERGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel Respiratorio","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L por alÃ©rgeno"}' WHERE nombre = 'PANEL RESPIRATORIO 20 ALERGENOS VENEZOLANO';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel Atopic","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L por alÃ©rgeno"}' WHERE nombre = 'PANEL DE ALERGIAS ATOPIC 20 ALERGENOS MIXTOS INHALANTES Y ALIMENTOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel PediÃ¡trico","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L por alÃ©rgeno"}' WHERE nombre = 'PANEL DE ALERGIAS PEDIATRICO 10 ALERGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Panel Medicamentos","unidad":"kUA/L","valor_referencial":"\u003c0.35 kUA/L por alÃ©rgeno"}' WHERE nombre = 'PANEL DE ALERGIAS A MEDICAMENTOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PAPP-A","unidad":"mIU/L","valor_referencial":"SegÃºn edad gestacional"}' WHERE nombre = 'PAPP-A';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PÃ©ptido C","unidad":"ng/mL","valor_referencial":"1.1-4.4 ng/mL"}' WHERE nombre = 'PEPTIDO C';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PepsinÃ³geno I","unidad":"ng/mL","valor_referencial":"28-100 ng/mL"}' WHERE nombre = 'PEPSINOGENO I (PGI)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PepsinÃ³geno II","unidad":"ng/mL","valor_referencial":"3-20 ng/mL"}' WHERE nombre = 'PEPSINOGENO II (PGI)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Perfil CelÃ­aco","unidad":"","valor_referencial":"Negativo para todos los antÃ­genos"}' WHERE nombre = 'PERFIL CELIACO 6 ANTIGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Perfil Hepatitis Autoinmune","unidad":"","valor_referencial":"Negativo para todos los antÃ­genos"}' WHERE nombre = 'PERFIL HEPATITIS AUTOINMUNE 10 ANTIGENOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Perfil Autoinmune","unidad":"","valor_referencial":"Negativo para todos los antÃ­genos"}' WHERE nombre = 'PERFIL AUTOINMUNE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Plomo","unidad":"Î¼g/dL","valor_referencial":"\u003c10 Î¼g/dL"}' WHERE nombre = 'PLOMO EN SANGRE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Potasio","unidad":"mEq/L","valor_referencial":"3.5-5.0 mEq/L"}' WHERE nombre = 'POTASIO (K)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Procalcitonina","unidad":"ng/mL","valor_referencial":"\u003c0.25 ng/mL"}' WHERE nombre = 'PROCALCITONINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Progesterona","unidad":"ng/mL","valor_referencial":"Fase lÃºtea: 5-20 ng/mL"}' WHERE nombre = 'PROGESTERONA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Prolactina","unidad":"ng/mL","valor_referencial":"Mujeres: 0-20 ng/mL, Hombres: 2.5-17 ng/mL"}' WHERE nombre = 'PROLACTINA (PRL)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PCR","unidad":"mg/L","valor_referencial":"\u003c3.0 mg/L"}' WHERE nombre = 'PROTEINA C REACTIVA (PCR)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PCR Ultrasensible","unidad":"mg/L","valor_referencial":"\u003c1.0 mg/L"}' WHERE nombre = 'PCR ULTRASENSIBLE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ProteÃ­nas Totales","unidad":"g/dL","valor_referencial":"6.0-8.3 g/dL"}' WHERE nombre = 'PROTEINAS TOTALES';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Proteinuria","unidad":"mg/24h","valor_referencial":"\u003c150 mg/24h"}' WHERE nombre = 'PROTEINURIA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"hCG Cualitativa","unidad":"","valor_referencial":"Negativo (No embarazada)"}' WHERE nombre = 'PRUEBA DE EMBARAZO EN SANGRE (HCG)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PSA Libre","unidad":"ng/mL","valor_referencial":"RelaciÃ³n PSA libre/total: \u003e25%"}' WHERE nombre = 'PSA LIBRE (AntÃ­geno ProstÃ¡tico Libre)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PSA Total","unidad":"ng/mL","valor_referencial":"\u003c4 ng/mL"}' WHERE nombre = 'PSA TOTAL (AntÃ­geno ProstÃ¡tico Total)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Tiempo de Protrombina","unidad":"segundos","valor_referencial":"11-15 segundos"},{"nombre":"INR","unidad":"","valor_referencial":"0.8-1.2"}]' WHERE nombre = 'PT (Tiempo de Protrombina)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PTT","unidad":"segundos","valor_referencial":"25-35 segundos"}' WHERE nombre = 'PTT (Tiempo Parcial de Tromboplastina)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Parvovirus B19 IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'PARVOVIRUS B19 IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Parvovirus B19 IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'PARVOVIRUS B19 IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"PTH","unidad":"pg/mL","valor_referencial":"15-65 pg/mL"}' WHERE nombre = 'PARATOHORMONA (PTH) INTACTA FRACCION 84';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Parotiditis IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'PAROTIDITIS IgM (MUMPS) IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Parotiditis IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'PAROTIDITIS IgG (MUMPS) IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"EosinÃ³filos","unidad":"cÃ©lulas/Î¼L","valor_referencial":"50-500 cÃ©lulas/Î¼L"}' WHERE nombre = 'RECUENTO DE EOSINOFILOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"RubÃ©ola IgG","unidad":"UI/mL","valor_referencial":"\u003c10 (Negativo), \u003e10 (Inmune)"}' WHERE nombre = 'RUBEOLA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"RubÃ©ola IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'RUBEOLA IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Rotavirus","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'ROTAVIRUS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SarampiÃ³n IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'SARAMPION (MEASLES) IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SarampiÃ³n IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'SARAMPION (MEASLES) IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Sangre Oculta","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'SANGRE OCULTA EN HECES';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Sangre Oculta + Transferrina","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'SANGRE OCULTA EN HECES + TRANSFERRINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SerologÃ­a Hongos","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'SEROLOGIA PARA HONGOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Serotonina","unidad":"ng/mL","valor_referencial":"50-200 ng/mL"}' WHERE nombre = 'SEROTONINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SARS-CoV-2 IgM/IgG","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'SINDROME RESPIRATORIO AGUDO SEVERO SARS-CoV-2 (IgM/IgG)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"SHBG","unidad":"nmol/L","valor_referencial":"Hombres: 18-54 nmol/L, Mujeres: 32-128 nmol/L"}' WHERE nombre = 'SHBG (Globulina Fijadora de Hormonas Sexuales)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Anti-Treponema","unidad":"S/CO","valor_referencial":"\u003c1.0 (Negativo)"}' WHERE nombre = 'SIFILIS (ANTICUERPOS ANTI-TREPONEMA IgM+IgG)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Sodio","unidad":"mEq/L","valor_referencial":"135-145 mEq/L"}' WHERE nombre = 'SODIO (NA)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Sudan III","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'SUDAN III';
UPDATE public.estudios SET campos_formulario = '{"nombre":"T3 Libre","unidad":"pg/mL","valor_referencial":"2.3-4.2 pg/mL"}' WHERE nombre = 'T3 LIBRE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"T3 Total","unidad":"ng/dL","valor_referencial":"80-200 ng/dL"}' WHERE nombre = 'T3 TOTAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"T4 Libre","unidad":"ng/dL","valor_referencial":"0.8-1.8 ng/dL"}' WHERE nombre = 'T4 LIBRE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"T4 Total","unidad":"Î¼g/dL","valor_referencial":"4.5-12.0 Î¼g/dL"}' WHERE nombre = 'T4 TOTAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Testosterona Libre","unidad":"pg/mL","valor_referencial":"9-30 pg/mL"}' WHERE nombre = 'TESTOSTERONA LIBRE';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Testosterona Total","unidad":"ng/dL","valor_referencial":"270-1070 ng/dL"}' WHERE nombre = 'TESTOSTERONA TOTAL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Tiroglobulina","unidad":"ng/mL","valor_referencial":"\u003c55 ng/mL"}' WHERE nombre = 'TIROGLOBULINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"AST (TGO)","unidad":"U/L","valor_referencial":"10-34 U/L"}' WHERE nombre = 'TGO (Transaminasa GlutÃ¡mico OxaloacÃ©tica)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"ALT (TGP)","unidad":"U/L","valor_referencial":"Hombres: \u003c45 U/L, Mujeres: \u003c35 U/L"}' WHERE nombre = 'TGP (Transaminasa GlutÃ¡mico PirÃºvica)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Toxoplasma IgG","unidad":"UI/mL","valor_referencial":"\u003c1.6 (Negativo)"}' WHERE nombre = 'TOXOPLASMA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Toxoplasma Avidez","unidad":"%","valor_referencial":"\u003e60% (Alta avidez)"}' WHERE nombre = 'TOXOPLASMA AVIDEZ';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Toxoplasma IgM","unidad":"Ãndice","valor_referencial":"\u003c0.5 (Negativo)"}' WHERE nombre = 'TOXOPLASMA IgM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Transferrina","unidad":"mg/dL","valor_referencial":"200-400 mg/dL"}' WHERE nombre = 'TRANSFERRINA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Transglutaminasa IgA","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'TRANSGLUTAMINASA IgA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Transglutaminasa IgG","unidad":"U/mL","valor_referencial":"\u003c20 U/mL"}' WHERE nombre = 'TRANSGLUTAMINASA IgG';
UPDATE public.estudios SET campos_formulario = '{"nombre":"TriglicÃ©ridos","unidad":"mg/dL","valor_referencial":"\u003c150 mg/dL"}' WHERE nombre = 'TRIGLICÃ‰RIDOS';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Troponina I","unidad":"ng/mL","valor_referencial":"\u003c0.04 ng/mL"}' WHERE nombre = 'TROPONINA CUANTIFICADA';
UPDATE public.estudios SET campos_formulario = '{"nombre":"TSH","unidad":"mIU/L","valor_referencial":"0.4-4.0 mIU/L"}' WHERE nombre = 'TSH';
UPDATE public.estudios SET campos_formulario = '{"nombre":"TSH Ultrasensible","unidad":"mIU/L","valor_referencial":"0.4-4.0 mIU/L"}' WHERE nombre = 'TSH ULTRASENSIBLE (4TA GENERACION)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"VDRL","unidad":"","valor_referencial":"No reactivo"}' WHERE nombre = 'V.D.R.L.';
UPDATE public.estudios SET campos_formulario = '{"nombre":"VSG","unidad":"mm/h","valor_referencial":"Hombres: \u003c15 mm/h, Mujeres: \u003c20 mm/h"}' WHERE nombre = 'V.S.G (VELOCIDAD DE SEDIMENTACIÃ“N GLOBULAR)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Vitamina B12","unidad":"pg/mL","valor_referencial":"200-900 pg/mL"}' WHERE nombre = 'VITAMINA B12';
UPDATE public.estudios SET campos_formulario = '{"nombre":"RSV IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'VIRUS SINCITIAL RESPIRATORIO IgM (RSV)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"RSV IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}' WHERE nombre = 'VIRUS SINCITIAL RESPIRATORIO IgG (RSV)';
UPDATE public.estudios SET campos_formulario = '{"nombre":"VLDL Colesterol","unidad":"mg/dL","valor_referencial":"\u003c30 mg/dL"}' WHERE nombre = 'VLDL COLESTEROL';
UPDATE public.estudios SET campos_formulario = '{"nombre":"Zinc","unidad":"Î¼g/dL","valor_referencial":"66-110 Î¼g/dL"}' WHERE nombre = 'ZINC (ZN)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Recuento","unidad":"UFC/mL","valor_referencial":"\u003c10,000 UFC/mL (Normal)"},{"nombre":"IdentificaciÃ³n","unidad":"","valor_referencial":"No se aÃ­slan microorganismos patÃ³genos"},{"nombre":"Sensibilidad","unidad":"","valor_referencial":"SegÃºn antibiograma"}]' WHERE nombre = 'UROCULTIVO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Flora Normal","unidad":"","valor_referencial":"Presente"},{"nombre":"Streptococcus Î²-hemolÃ­tico","unidad":"","valor_referencial":"Ausente"}]' WHERE nombre = 'EXUDADO FARÃNGEO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"IdentificaciÃ³n","unidad":"","valor_referencial":"No se aÃ­slan microorganismos patÃ³genos"},{"nombre":"Sensibilidad","unidad":"","valor_referencial":"SegÃºn antibiograma"}]' WHERE nombre = 'CULTIVOS DE SECRECIONES (VARIAS)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Salmonella","unidad":"","valor_referencial":"Ausente"},{"nombre":"Shigella","unidad":"","valor_referencial":"Ausente"},{"nombre":"Campylobacter","unidad":"","valor_referencial":"Ausente"}]' WHERE nombre = 'COPROCULTIVO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Crecimiento","unidad":"","valor_referencial":"Negativo"},{"nombre":"IdentificaciÃ³n","unidad":"","valor_referencial":"No se aÃ­slan microorganismos"}]' WHERE nombre = 'HEMOCULTIVO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Gram Positivos","unidad":"","valor_referencial":"SegÃºn muestra"},{"nombre":"Gram Negativos","unidad":"","valor_referencial":"SegÃºn muestra"}]' WHERE nombre = 'TINCIÃ“N DE GRAM';
UPDATE public.estudios SET campos_formulario = '{"nombre":"BAAR","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'TINCIÃ“N DE ZIEHL NEELSEN';
UPDATE public.estudios SET campos_formulario = '{"nombre":"BAAR","unidad":"","valor_referencial":"Negativo"}' WHERE nombre = 'TINCIÃ“N DE KINYOUN';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"FSH","unidad":"mIU/mL","valor_referencial":"Fase folicular: 3-10 mIU/mL"},{"nombre":"LH","unidad":"mIU/mL","valor_referencial":"2-10 mIU/mL"},{"nombre":"Estradiol","unidad":"pg/mL","valor_referencial":"Fase folicular: 30-120 pg/mL"},{"nombre":"Prolactina","unidad":"ng/mL","valor_referencial":"0-20 ng/mL"},{"nombre":"Progesterona","unidad":"ng/mL","valor_referencial":"Fase lÃºtea: 5-20 ng/mL"}]' WHERE nombre = 'PERFIL HORMONAL FEMENINO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"TSH","unidad":"mIU/L","valor_referencial":"0.4-4.0 mIU/L"},{"nombre":"T3 Libre","unidad":"pg/mL","valor_referencial":"2.3-4.2 pg/mL"},{"nombre":"T4 Libre","unidad":"ng/dL","valor_referencial":"0.8-1.8 ng/dL"}]' WHERE nombre = 'PERFIL TIROIDEO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Hemograma","unidad":"","valor_referencial":"Ver hemograma completo"},{"nombre":"Glucosa","unidad":"mg/dL","valor_referencial":"70-100 mg/dL"},{"nombre":"Urea","unidad":"mg/dL","valor_referencial":"7-25 mg/dL"},{"nombre":"Creatinina","unidad":"mg/dL","valor_referencial":"0.6-1.3 mg/dL"},{"nombre":"HIV","unidad":"","valor_referencial":"Negativo"},{"nombre":"VDRL","unidad":"","valor_referencial":"No reactivo"},{"nombre":"TP","unidad":"seg","valor_referencial":"11-15 seg"},{"nombre":"PTT","unidad":"seg","valor_referencial":"25-35 seg"},{"nombre":"Grupo SanguÃ­neo","unidad":"","valor_referencial":"A, B, AB, O + Rh"}]' WHERE nombre = 'PERFIL PRE OPERATORIO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Colesterol Total","unidad":"mg/dL","valor_referencial":"\u003c200 mg/dL"},{"nombre":"HDL Colesterol","unidad":"mg/dL","valor_referencial":"Hombres: \u003e40 mg/dL, Mujeres: \u003e50 mg/dL"},{"nombre":"LDL Colesterol","unidad":"mg/dL","valor_referencial":"\u003c100 mg/dL"},{"nombre":"VLDL Colesterol","unidad":"mg/dL","valor_referencial":"\u003c30 mg/dL"},{"nombre":"TriglicÃ©ridos","unidad":"mg/dL","valor_referencial":"\u003c150 mg/dL"}]' WHERE nombre = 'PERFIL LIPÃDICO';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Sodio","unidad":"mEq/L","valor_referencial":"135-145 mEq/L"},{"nombre":"Potasio","unidad":"mEq/L","valor_referencial":"3.5-5.0 mEq/L"},{"nombre":"Cloro","unidad":"mEq/L","valor_referencial":"96-106 mEq/L"}]' WHERE nombre = 'ELECTROLITOS';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Glucosa Basal","unidad":"mg/dL","valor_referencial":"70-100 mg/dL"},{"nombre":"Glucosa Post-Prandial","unidad":"mg/dL","valor_referencial":"\u003c140 mg/dL"},{"nombre":"Insulina Basal","unidad":"Î¼U/mL","valor_referencial":"2.6-24.9 Î¼U/mL"},{"nombre":"Insulina Post-Prandial","unidad":"Î¼U/mL","valor_referencial":"SegÃºn protocolo"}]' WHERE nombre = 'GLICEMIA E INSULINA (BASAL Y POST PRANDIAL)';
UPDATE public.estudios SET campos_formulario = '[{"nombre":"Toxoplasma IgG","unidad":"UI/mL","valor_referencial":"\u003c1.6 (Negativo)"},{"nombre":"Toxoplasma IgM","unidad":"Ãndice","valor_referencial":"\u003c0.5 (Negativo)"},{"nombre":"RubÃ©ola IgG","unidad":"UI/mL","valor_referencial":"\u003e10 (Inmune)"},{"nombre":"RubÃ©ola IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"CMV IgG","unidad":"UA/mL","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"CMV IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"Herpes I IgG","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"},{"nombre":"Herpes I IgM","unidad":"Ãndice","valor_referencial":"\u003c0.9 (Negativo)"}]' WHERE nombre = 'T.O.R.C.H';
